name: cloc
on:
  pull_request_target:
    branches:
    - main
    types:
    - ready_for_review

# Cancel the workflow in progress in newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  TARGET: "code"
  EXT: "py"

jobs:
  cloc:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          path: pr
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base
      - name: Count Lines Of Code
        id: loc
        run: |
          pip install tabulate
          # pseudo rand EOF value
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "loc_content<<$EOF" >> "$GITHUB_ENV"
          echo "base LOC" >> "$GITHUB_ENV"
          cd /base && ./sz.py >> "$GITHUB_ENV"
          echo "PR LOC" "$GITHUB_ENV"
          rm ./pr/sz.py && cp ./base/sz.py ./pr/
          cd /pr && ./sz.py >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

      - name: Comment Code Lines
        continue-on-error: false
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          recreate: true
          header: LOC
          message: |
            ### Lines Of Code
            ```
            ${{ env.loc_content }}
            ```

